#!/usr/bin/env node
// Post-process Emscripten output into a single .ts module:
//   - reads the .wasm binary, base64-encodes it
//   - reads the .mjs ES-module factory glue
//   - emits a TS module that exports `instantiate()` returning the typed module,
//     supplying `wasmBinary` so the factory never tries to fetch/fs the binary.
//
// Usage: node inline-wasm.mjs <wasm-path> <mjs-path> <out-ts-path>

import { readFileSync, writeFileSync } from "node:fs";

const [wasmPath, mjsPath, outPath] = process.argv.slice(2);
if (!wasmPath || !mjsPath || !outPath) {
    console.error("usage: inline-wasm.mjs <wasm> <mjs> <out.ts>");
    process.exit(1);
}

const wasm = readFileSync(wasmPath);
const wasmB64 = wasm.toString("base64");

let glue = readFileSync(mjsPath, "utf8");

// Strip the trailing `export default createWasmDsp;` — we re-export via our
// own `instantiate` wrapper. Match either with or without trailing semicolon
// and surrounding whitespace.
glue = glue.replace(/\bexport\s+default\s+createWasmDsp\s*;?\s*$/m, "");

// The emitted glue references `import.meta.url` to derive a base for fetching
// the sibling .wasm. We always supply `wasmBinary` so the fetch path never
// runs, and we also supply `locateFile` so the glue's `findWasmBinary` takes
// the `locateFile` branch instead of evaluating `new URL("wasm-dsp.wasm",
// import.meta.url)`. That URL constructor throws "Invalid URL" inside Vite's
// `?worker&inline` blob workers (the blob's `import.meta.url` is opaque), so
// short-circuiting it is necessary even though the result is otherwise
// dead-code.

const banner = `// @ts-nocheck
// AUTO-GENERATED by scripts/build-wasm.sh + scripts/inline-wasm.mjs.
// Source: vendor/pffft + vendor/libebur128. DO NOT edit by hand.
// To regenerate, activate emsdk and run: pnpm build:wasm
/* eslint-disable */

const WASM_BASE64 = "${wasmB64}";

function decodeWasmBase64(b64) {
    if (typeof Buffer !== "undefined") {
        const buf = Buffer.from(b64, "base64");
        return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
    }
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}

`;

const footer = `
let _instance = null;

export async function instantiate() {
    if (_instance) return _instance;
    _instance = await createWasmDsp({
        wasmBinary: decodeWasmBase64(WASM_BASE64),
        locateFile: (path) => path,
    });
    return _instance;
}

export function getInstance() {
    if (!_instance) {
        throw new Error("wasm-dsp not instantiated — await instantiate() first");
    }
    return _instance;
}

export function __resetForTests() {
    _instance = null;
}
`;

writeFileSync(outPath, banner + glue + footer);
console.log(`Wrote ${outPath} (${(banner.length + glue.length + footer.length) / 1024 | 0} KB, wasm ${wasm.length} B → ${wasmB64.length} B base64)`);
