#!/usr/bin/env node
// Post-process the Emscripten -sWASM=0 (asm.js) output into a single .ts
// module that exports the `createJsDsp` factory. No .wasm binary involved;
// the factory contains the numeric kernels inline as JS.
//
// Usage: node inline-js-dsp.mjs <mjs-path> <out-ts-path>

import { readFileSync, writeFileSync } from "node:fs";

const [mjsPath, outPath] = process.argv.slice(2);
if (!mjsPath || !outPath) {
    console.error("usage: inline-js-dsp.mjs <mjs> <out.ts>");
    process.exit(1);
}

let glue = readFileSync(mjsPath, "utf8");

// Strip the trailing `export default createJsDsp;` — the loader imports the
// factory directly via the named export below.
glue = glue.replace(/\bexport\s+default\s+createJsDsp\s*;?\s*$/m, "");

const banner = `// @ts-nocheck
// AUTO-GENERATED by scripts/build-js-dsp.sh + scripts/inline-js-dsp.mjs.
// Source: vendor/pffft + vendor/libebur128. DO NOT edit by hand.
// To regenerate, activate emsdk and run: pnpm build:js-dsp
/* eslint-disable */

`;

const footer = `
export { createJsDsp };
`;

writeFileSync(outPath, banner + glue + footer);
console.log(`Wrote ${outPath} (${(banner.length + glue.length + footer.length) / 1024 | 0} KB)`);
